version: '2'
services:
app:
image: 'chaashish/bankingapptest.jar:latest'
build:
context:
container_name: app
restart: always
ports:
- 8080:8080
depends_on:
- db
environment:
- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Comany_DB
- SPRING_DATASOURCE_USERNAME=some-postgres
- SPRING_DATASOURCE_PASSWORD=mysecretpassword
- SPRING_JPA_HIBERNATE_DDL_AUTO=update
db:

    image: 'postgres:13.1-alpine'

    container_name: db

    environment:
- POSTGRES_USER=some-postgres
- POSTGRES_PASSWORD=mysecretpassword
- POSTGRES_DB=Comany_DB
expose:
- "5432:5432"